name: "linux tests and documentation builds for 'kiara_plugin.streamlit'"
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:

#  commitlint:
#    name: lint commit message
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: wagoid/commitlint-github-action@v4

  test-linux:
    name: pytest on linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: "Set up Python ${{ matrix.python_version }}"
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python_version }}"
      - uses: actions/checkout@v3
      - name: install kiara_plugin.streamlit
        run: pip install -U .[all,dev_testing]
      - name: display installed kiara and module package versions
        run: pip list | grep kiara
      - name: Test with pytest
        run: make test

#  coverage:
#    name: create and publish test coverage
#    runs-on: ubuntu-latest
#    steps:
#      - name: "Set up Python 3.9"
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.9"
#      - uses: actions/checkout@v3
#      - name: install kiara
#        run: pip install -U .[all,dev_testing]
#      - name: display installed kiara and module package versions
#        run: pip list | grep kiara
#      - name: Run coverage
#        run: coverage run -m pytest tests
#      - name: coverallsUpload coverage data to coveralls.io
#        uses: coverallsapp/github-action@v2

  mypy-linux:
    name: mypy check on linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: "Set up Python ${{ matrix.python_version }}"
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python_version }}"
      - uses: actions/checkout@v3
      - name: install kiara_plugin.streamlit
        run: pip install -U .[all,dev_testing]
      - name: Test with mypy
        run: make mypy

  linting-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: pip cache
        id: pip-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.*') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U ruff
      # Include `--format=github` to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff --output-format=github src/

  build_python_package:
    name: build python package
    runs-on: ubuntu-latest
    needs:
      - test-linux
      - mypy-linux
      - linting-linux
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install pip
        run: pip install -U pip setuptools setuptools_scm build
      - name: create packages
        run: python -m build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-dists
          path: dist/

  release_python_package:
    name: publish python package to pypi
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs:
      - build_python_package
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Retrieve build distributions
        uses: actions/download-artifact@v3
        with:
          name: build-dists
          path: dist/
      - name: publish to PyPI  # make sure you have pypi trusted publishing configured for this repo
        uses: pypa/gh-action-pypi-publish@release/v1

  build_and_release_conda_package:
    name: conda package build (and upload if release)
    runs-on: ubuntu-latest
    needs:
      - test-linux
      - mypy-linux   # uncomment if this step is enabled
      - linting-linux   # uncomment if this step is enabled
    steps:
      - name: "Set up Python 3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: pip cache
        id: pip-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.*') }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install kiara
        run: pip install kiara
      - name: install required plugin packages
        run: pip install git+https://github.com/DHARPA-Project/kiara_plugin.develop.git@develop
      - name: build conda package
        if: ${{ ( github.ref == 'refs/heads/develop') }}
        run: kiara conda build-package --patch-data ci/conda/conda-pkg-patch.yaml .
      - name: extract tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: build & publish conda package
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: kiara conda build-package --publish --user dharpa --token ${{ secrets.ANACONDA_PUSH_TOKEN }} --patch-data ci/conda/conda-pkg-patch.yaml .

  merge_tag_to_main:
    name: merge current tag to main branch
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - release_python_package
      - build_and_release_conda_package
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: git config --global user.email "markus@frkl.io"
    - run: git config --global user.name "Markus Binsteiner"
    - name: extract tag name
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: checkout main branch
      run: git checkout main
    - name: merge tag
      run: git merge "${RELEASE_VERSION}"
    - name: push updated main branch
      run: git push https://${{ secrets.GITHUB_TOKEN }}@github.com/DHARPA-Project/kiara_plugin.streamlit.git
